services:
  watch-playwright:
    image: watch-playwright
    restart: unless-stopped

  watch-sender:
    image: watch-sender
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}

  watch-runner:
    image: watch-runner
    restart: unless-stopped
    depends_on:
      - watch-playwright
      - watch-sender
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8001:8080"

  crawler-workhub:
    image: crawler-workhub
    restart: unless-stopped
    depends_on:
      - watch-playwright

  crawler-saramin:
    image: crawler-saramin
    restart: unless-stopped
    depends_on:
      - watch-playwright
    environment:
      - SEARCH_KEYWORD=${SARAMIN_KEYWORD}

  crawler-wanted:
    image: crawler-wanted
    restart: unless-stopped
    depends_on:
      - watch-playwright
    environment:
      - SEARCH_KEYWORD=${WANTED_KEYWORD}

  watch-ai:
    image: watch-ai
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  crawler-yt-channels:
    image: crawler-yt-channels
    restart: unless-stopped
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}

  crawler-kakao-channels:
    image: crawler-kakao-channels
    restart: unless-stopped
    depends_on:
      - watch-playwright
